<a href="https://colab.research.google.com/github/a2r4vind/Machine-Learning-Models/blob/main/Gated_Recurrent_Unit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implement RNN program using Gated Recurrent Unit (GRU) for sequence prediction using TensorFlow

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense

# Generate synthetic data

In [2]:
np.random.seed(42)
sequence_length = 10
num_samples = 1000
input_dim = 1

In [3]:
X = np.random.random((num_samples, sequence_length, input_dim))
y = np.sum(X, axis=1)

In [5]:
print(X)
print()
print(y)

[[[0.37454012]
  [0.95071431]
  [0.73199394]
  ...
  [0.86617615]
  [0.60111501]
  [0.70807258]]

 [[0.02058449]
  [0.96990985]
  [0.83244264]
  ...
  [0.52475643]
  [0.43194502]
  [0.29122914]]

 [[0.61185289]
  [0.13949386]
  [0.29214465]
  ...
  [0.51423444]
  [0.59241457]
  [0.04645041]]

 ...

 [[0.066628  ]
  [0.97607969]
  [0.95699177]
  ...
  [0.83017724]
  [0.95061177]
  [0.63425265]]

 [[0.35390567]
  [0.60332557]
  [0.31200131]
  ...
  [0.29338968]
  [0.03341799]
  [0.81582085]]

 [[0.45038321]
  [0.32513293]
  [0.47111035]
  ...
  [0.94670792]
  [0.39748799]
  [0.2171404 ]]]

[[5.20136736]
 [3.95267841]
 [4.00387239]
 [5.09270689]
 [4.04557017]
 [5.75385094]
 [4.67370654]
 [4.54745829]
 [5.24361489]
 [4.50324846]
 [4.11933711]
 [6.11579849]
 [4.98307459]
 [4.92033325]
 [3.77645242]
 [5.40949019]
 [4.23395228]
 [4.40420426]
 [5.3184244 ]
 [6.50210531]
 [3.33282357]
 [5.63703528]
 [5.08579754]
 [4.41223638]
 [7.33465383]
 [4.87332154]
 [5.93419925]
 [7.35866477]
 [4.19740497]

# Split the data into training and testing sets

In [4]:
split_ratio = 0.8
split_index = int(split_ratio * num_samples)
X_train, X_test = X[:split_index], X[split_index: ]
y_train, y_test = y[:split_index], y[split_index: ]

In [6]:
print('X_train: ', X_train)
print('X_test: ', X_test)
print('y_train: ', y_train)
print('y_test: ', y_test)

X_train:  [[[0.37454012]
  [0.95071431]
  [0.73199394]
  ...
  [0.86617615]
  [0.60111501]
  [0.70807258]]

 [[0.02058449]
  [0.96990985]
  [0.83244264]
  ...
  [0.52475643]
  [0.43194502]
  [0.29122914]]

 [[0.61185289]
  [0.13949386]
  [0.29214465]
  ...
  [0.51423444]
  [0.59241457]
  [0.04645041]]

 ...

 [[0.98265241]
  [0.63704755]
  [0.16163769]
  ...
  [0.75746905]
  [0.73170527]
  [0.7091807 ]]

 [[0.20033982]
  [0.21100669]
  [0.688293  ]
  ...
  [0.45326177]
  [0.79218994]
  [0.8386218 ]]

 [[0.65477575]
  [0.22842585]
  [0.27401178]
  ...
  [0.45532875]
  [0.90843755]
  [0.10448032]]]
X_test:  [[[0.72026792]
  [0.687283  ]
  [0.0957542 ]
  ...
  [0.25736546]
  [0.69350984]
  [0.03971121]]

 [[0.83940804]
  [0.44817085]
  [0.63669291]
  ...
  [0.61772692]
  [0.45632592]
  [0.89409137]]

 [[0.49786918]
  [0.84180871]
  [0.80135206]
  ...
  [0.22763254]
  [0.52443635]
  [0.80609675]]

 ...

 [[0.066628  ]
  [0.97607969]
  [0.95699177]
  ...
  [0.83017724]
  [0.95061177]
  [0.6

# Build the GRU Model

In [7]:
model = Sequential()
model.add(GRU(10, input_shape=(sequence_length, input_dim), activation="relu"))
model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


# Compile the model

In [8]:
model.compile(optimizer="adam", loss='mean_squared_error')

# Train the model

In [9]:
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 24.0787 - val_loss: 22.7624
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.9746 - val_loss: 21.6170
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.5506 - val_loss: 20.1522
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.1527 - val_loss: 18.1770
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.7484 - val_loss: 15.2939
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.2061 - val_loss: 10.5182
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.5724 - val_loss: 2.1774
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1019 - val_loss: 0.2877
Epoch 9/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2750 - val_loss: 0.2234
Epoch 10/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2360 - val_loss: 0.1921
Epoch 11/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1888 - val_loss: 0.1587
Epoch 12/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.

# Evaluate the model on the test data

In [10]:
test_loss = model.evaluate(X_test, y_test)
print('Test loss: ', test_loss)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0132
Test loss:  0.013095715083181858


# Make the predictions

In [11]:
predictions = model.predict(X_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


# Print few predictions and their corresponding values

In [12]:
for i in range(5):
  print(f'Predicted Value: {predictions[i][0]}, Actual Values: {y_test[i]}')

Predicted Value: 5.201446533203125, Actual Values: [5.10520034]
Predicted Value: 5.937058448791504, Actual Values: [6.03618101]
Predicted Value: 5.524447441101074, Actual Values: [5.5720844]
Predicted Value: 4.537613868713379, Actual Values: [4.68995643]
Predicted Value: 4.237005233764648, Actual Values: [4.29333816]
